### ISSUE TITLE
Menu layout in pattern_gui.py

### ISSUE THREAD

**Issue by RupertB-ES** [CrashOverride85/zc95#35]
It would be good to add a gui_column tag to menu items in scripts - could be single or groups
![zc95cols](https://github.com/CrashOverride85/zc95/assets/61495510/dc9fb470-db9d-4eac-9326-77a20dd94dc7)

**Comment by CrashOverride85** [comment]
Interesting idea, I'll see if I can add this, but there's a couple of things I'm working on before that

**Comment by CrashOverride85** [comment]
v1.6 now allows "group" to be specified in Lua scripts
