### ISSUE TITLE
A few small build notes

### ISSUE THREAD

**Issue by shiny-mira** [CrashOverride85/zc95#36]
Hi,

thank you very much for creating this repository. This is an awesome project.

I finished building my first zc95 a couple of weeks ago - and I have one small comment that might be neat for the manual, plus a couple of notes about deprecated components (with replacements for most of them).

For the "Front panel controls" board, it might be nice to somehow note the orientation of the PCF8591 - I don't think that it is currently indicated on the board; I had to look it up in the Kicad files.

To continue with the PCF8591 - sadly, NXP just EOL-ed that chip, and it will not be available after January 2024. The  notice for this is available here: https://media.digikey.com/pdf/PCNs/NXP/202306034DN%20.pdf. I am not sure if there is an easy substitute for it.

Two of the LCSC components are no longer available; there are easy substitutes for them.

For the front panel controls, C191532 is discontinued; I used C216315 instead. Main & output boards: C50984 -> C124410

Thank you very much again,
 Mira

**Comment by CrashOverride85** [comment]
Thanks for your feedback 🙂
Those suggestions look good, thanks, I'll try and update the BoM and build notes this week. 

I'm not sure what to do about the PCF8591 yet, I was trying to keep that board as easy to hand solder as possible, and IIRC that didn't leave many choices at all for the ADC.
Hopefully it's still going to be available for a while yet, whilst I figure out what to swap it for - thanks for the warning.

**Comment by CrashOverride85** [comment]
Build notes & BoM updated, thanks :+1:
