### ISSUE TITLE
Wifi Config AP mode fails - add note to docs about known issue

### ISSUE THREAD

**Issue by jlatex** [CrashOverride85/zc95#46]
With 1.6 release and with current git head, after selecting 'config wifi/ap mode' on the UI the UI freezes and the box is unresponsive.  Serial log:

```
CMenuApMode()
SetupWebInterface()
Loop time: 514, batt: 100
CAnalogueCapture::stop()
CAnalogueCapture::stop() done
CMenuApMode::wifi_scan(): Start scanning for wifi networks
CWifi::init(): wifi/cyw43 init success
dhcp_release_and_stop()
```

Since this is a new box I've not had this working yet

**Comment by jlatex** [comment]
Oh, this might be https://github.com/CrashOverride85/zc95/discussions/25 I'll try that!

**Comment by jlatex** [comment]
Okay, this is #25 and our friends box has the same problem, so suggest adding a note to the discussion from the docs for now until there's a solution.  Updated title of this issue

**Comment by CrashOverride85** [comment]
Thanks for reporting this - I'm going to treat this more as a bug in the design (poor choice of MOSFET as you've identified), than just a documentation issue. Although short term, I agree that's a good idea.

**Comment by CrashOverride85** [comment]
Added to known issues, will look for a more suitable mosfet

**Comment by jlatex** [comment]
![20230815_125219](https://github.com/CrashOverride85/zc95/assets/89390295/6829ef97-bb8d-413c-8de9-cb9e5b73ab4b)

**Comment by CrashOverride85** [comment]
Ahh cool, good to know it works, thanks for letting me know. I'm going to try a smaller diode when it arrives, and update BoM & build notes to match
