### ISSUE TITLE
Confused menu when you have no audio board with 1.6

### ISSUE THREAD

**Issue by jlatex** [CrashOverride85/zc95#54]
seemed to happen occasionally after using a mode the menu would be a bit confused, without an audio board the menu doesn't show the audio modes, but you occasionally get them anway:

reproducer for me: turn box on, select triggered climb, hit back, select climb with pulse - you get audio threshold instead, and the menu options now don't match what you get.

**Comment by CrashOverride85** [comment]
Thanks for reporting this, should be fixed in the next version

**Comment by jlatex** [comment]
works!
